### ISSUE TITLE
Adding helpers methods to connect to arduino

### ISSUE THREAD

**Issue by cyprien-pixngraph** [fourquet/meteor-package-serialport#4]
Hi,
I've worked on serialport under meteor and i would like to share what i've done.
But i'm just starting with meteor so i don't know if the code i've written could be reused... Perharps it's possible to integrate it in your package ?
The goal is to have something that :
- List all the serial port (SerialPort.list function)
- Connect the serial port
- Read data from the SerialPort object (if connected)
- Write data to the SerialPort object (if connected)
Your example is nice but is using meteor steams and is not compatible with meteor > 0.9.0
Have you the time to help me develop this ?
Do you think this is not the place to have this discussion (perhaps it will be better to use meteor forum) ?
Thanks for your help, 
Cyprien

**Comment by donaldaverill** [comment]
Hi Cyprien,

Yeah, I'm happy to help out and if you'd like to add features, I can maintain the package. Pull requests might be the best option to add code. So, if you want to send me changes that way, I can update the package and republish to atmosphere. What do you have in mind regarding server/client communications? The code from meteor streams could be adapted to work with this package. As far as I can tell, it's basically method calls from the client to the server and publications without mongo collections from server to client, which would be pretty straightforward to recreated. Or something like [Streamy](https://atmospherejs.com/yuukan/streamy) would work instead of arunoda's package, which is dead like you mentioned.

**Comment by donaldaverill** [comment]
Closed...nothing to do.
